work_dir: 'resnext101_64x4d_baseline'

data:


model:
  name: 'resnex'
  pretrained: 'imagenet'
  version:  'resnext101_64x4d'

train:
  batch_size: 128
  num_epochs: 10
  early_stop_patience: 3

loss:
  name: "CrossEntropy"

optimizer:
  name: 'Adam'
  params:
    lr: 1.0e-3

scheduler:
  name: 'plateau'

num_workers: 2
device: 'cuda'