work_dir: 'se_resnext101_32x4d_2020_2_04/'

data:
  image_size: 128
  params:
    idx: 0
    fold_csv: 'train_with_fold_seed12.csv'

# Pretrained CNN
model:
  version:  'se_resnext101_32x4d'
  pretrained: 'imagenet'

train:
  batch_size: 128
  num_epochs: 60
  mixup: 0.4
  cutmix: 0.4
  accumulation_size: 256
  resume: No
  
loss:
  name: "OHEM"
  rate: 0.7

optimizer:
    name: 'SGD'
    params:
        lr: 0.01
        momentum: 0.9
        weight_decay: 1.0e-4
    lookahead:
        apply: Yes

scheduler:
  name: 'plateau'

num_workers: 2
device: 'cuda'