work_dir: 'se_resnext50_32x4d_11/'  
data:   
  image_size: 128
  params:
    idx: 0
    fold_csv: 'train_with_fold_seed12.csv'
  

model:   
  version:  'se_resnext50_32x4d'   
  pretrained: Yes
  
# SVHNPolicy dropoutなし、pa=7, fac=.8
transforms:     
  affine: No     
  crop: No
  threshold: 0.   
  sigma: 0.  
  autoaugment_ratio: 1.
  blur_ratio: 0.
  noise_ratio: 0.
  cutout_ratio: 0.
  grid_distortion_ratio: 0.     
  random_brightness_ratio: 0.     
  piece_affine_ratio: 0.     
  ssr_ratio: 0.3 
  grid_mask_ratio: 0. 
  augmix_ratio: 0.   
  
train:   
  batch_size: 128
  num_epochs: 200  
  mixup: 0.
  cutmix: 1. 
  grid_mask: 0.
  augmix: 0.   
  accumulation_size: 0 
  resume: Yes    
  path: '/home/kazuki/workspace/kaggle_bengali/result/se_resnext50_32x4d_2020_3_03/checkpoints/92.pth'
  
loss:   
  name: "CrossEntropy"  
  
optimizer:
    name: 'Adam'
    params:
        lr: 1.0e-3
        opt_eps: 1.0e-8
        weight_decay: 1.0e-4
    lookahead:
        apply: No

scheduler:   
  name: 'plateau'  
  
num_workers: 8
device: 'cuda' 