work_dir: 'look_ahed_adm_se_resnext101_32x4d'

data:
  image_size: 128
  params:
    idx: 0
    fold_csv: 'train_with_fold_seed12.csv'


model:
  version:  'se_resnext101_32x4d'

train:
  batch_size: 128
  num_epochs: 10
  early_stop_patience: 5

loss:
  name: "CrossEntropy"

optimizer:
  name: 'Adam'
  params:
    lr: 1.0e-3
  look_ahed:
    apply: Yes
    la_steps: 5.0
    la_alpha: 0.5

scheduler:
  name: 'plateau'

num_workers: 2
device: 'cuda'