work_dir: 'look_ahed_adam_se_resnext101_32x4d_2020_1_26'

data:
  image_size: 128
  params:
    idx: 0
    fold_csv: 'train_with_fold_seed12.csv'


model:
  version:  'se_resnext101_32x4d'

train:
  batch_size: 128
  num_epochs: 80
  accumulation_size: 256
  
loss:
  name: "CrossEntropy"

optimizer:
  name: 'SGD'
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 1.0e-4
  look_ahed:
    apply: Yes
    la_steps: 5.0
    la_alpha: 0.5

scheduler:
  name: 'plateau'

num_workers: 2
device: 'cuda'