work_dir: 'se_resnext101_32x4d_sgd'

data:
    image_size: 128
    params:
      idx: 0
      fold_csv: 'train_with_fold_seed12.csv'


model:
  pretrained: 'imagenet'
  version:  'se_resnext101_32x4d'

train:
  batch_size: 128
  num_epochs: 20
  early_stop_patience: 3

loss:
  name: "CrossEntropy"

optimizer:
  name: 'SGD'
  params:
    lr: 1.0e-3
    momentum: 0.9
    weight_decay: 1.0e-4

scheduler:
  name: 'plateau'

num_workers: 2
device: 'cuda'