work_dir: 'se_resnext101_32x4d_1/'  
data:   
  image_size: 128
  params:
    idx: 0
    fold_csv: 'train_with_fold_seed12.csv'
  

model:   
  version:  'se_resnext101_32x4d'   
  pretrained: 'imagenet'  
  
# SVHNPolicy 
train:   
  batch_size: 32
  num_epochs: 150   
  mixup: 0.
  cutmix: 0.   
  grid_mask: 0.
  augmix: 0.   
  accumulation_size: 0 
  resume: No    
  
loss:   
  name: "CrossEntropy"  
  
optimizer:
    name: 'Adam'
    params:
        lr: 1.0e-4
        opt_eps: 1.0e-8
        weight_decay: 1.0e-4
    lookahead:
        apply: No

scheduler:   
  name: 'plateau'  
  
num_workers: 16 
device: 'cuda' 