work_dir: 'se_resnext101_32x4d_2020_2_11/'

data:
  image_size: 224
  params:
    idx: 0
    fold_csv: 'train_with_fold_seed12.csv'

# Not
model:
  version:  'se_resnext101_32x4d'
  pretrained: 'imagenet'

# auto aug or aug mix 
transforms:
    affine: Yes
    crop: No
    threshold: 0.
    sigma: 0.
    blur_ratio: 0.
    noise_ratio: 0.
    cutout_ratio: 0.
    grid_distortion_ratio: 0.
    random_brightness_ratio: 0.
    piece_affine_ratio: 0.
    ssr_ratio: 0.5
    grid_mask_ratio: 0.3
    augmix_ratio: 0.
    
train:
  batch_size: 32
  num_epochs: 100
  mixup: 0.4
  cutmix: 0.4
  accumulation_size: 256
  resume: Yes
  
loss:
  name: "CrossEntropy"

optimizer:
    name: 'RAdam'
    params:
        lr: 1.0e-4
        opt_eps: 1.0e-8
        weight_decay: 1.0e-4
    lookahead:
        apply: Yes

# cosine scheduler epoch数
scheduler:
  name: 'plateau'

num_workers: 2
device: 'cuda' 