work_dir: 'se_resnext101_32x4d_2020_2_02/'

data:
  image_size: 128
  params:
    idx: 1
    fold_csv: 'train_with_fold_seed12.csv'


model:
  version:  'se_resnext101_32x4d'
  pretrained: 'imagenet'

train:
  batch_size: 128
  num_epochs: 40
  mixup: Yes
  accumulation_size: 256
  resume: No
  
loss:
  name: "CrossEntropy"

optimizer:
  name: 'RAdam'
  params:
    lr: 0.01
    opt_eps: 1.0e-8
    weight_decay: 1.0e-4
  lookahead:
    apply: Yes

scheduler:
  name: 'plateau'

num_workers: 2
device: 'cuda'