work_dir: 'se_resnext101_32x4d_2020_2_03/'

data:
  image_size: 128
  params:
    idx: 0
    fold_csv: 'train_with_fold_seed12.csv'

# Pretrained CNN
model:
  version:  'se_resnext101_32x4d'
  pretrained: 'imagenet'

train:
  batch_size: 128
  num_epochs: 30
  mixup: 0.4
  cutmix: 0.4
  accumulation_size: 256
  resume: Yes

transforms:
  affine: Yes
  crop: No
  threshold: 0.
  sigma: 0.
  blur_ratio: 0.
  noise_ratio: 0.
  cutout_ratio: 0.
  grid_distortion_ratio: 0.
  random_brightness_ratio: 0.
  piece_affine_ratio: 0.
  ssr_ratio: 0.
  
loss:
  name: "OHEM"
  rate: 0.7

optimizer:
    name: 'Adam'
    params:
        lr: 0.00001
        opt_eps: 1.0e-8
        weight_decay: 1.0e-4
    lookahead:
        apply: No

scheduler:
  name: 'plateau'

num_workers: 2
device: '1'